apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ztdietmaier/test1:main
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:h2:mem:camunda;DB_CLOSE_DELAY=1000"
        - name: DB_DRIVER
          value: "org.h2.Driver"
        - name: DB_USERNAME
          value: "sa"
        - name: DB_PASSWORD
          value: ""

